version: '3.7'

networks:
  mynetwork:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  app:
    container_name: app
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: ["docker/app.sh"]
    depends_on:
      - redis
    networks:
      - mynetwork